# Site settings
title: The Muties
email: themutiesrocknrollband@gmail.com
url: https://themuties.bandcamp.com/
description: "Psychedelic-garage-punk-rock’n’roll band from Cincinnati, Ohio"
keywords: "The Muties™, punk rock band, experimental music, Toxic Waste Barrel album, cosmic rock, Ohio music scene, Kentucky bands, Midwest music, Jake Taylor musician, Devin Fields drummer, Matt Stewart guitarist, Charlie Taylor guitarist, Paul Vine bassist, punk'n'roll space dust, raw rock energy, cosmic experimentation, audacious fusion music, psychedelic punk, unrefined energy, live band experience, wild and bizarre music, unique rock sound, sentient sludge, cosmic vivarium, lovesick music soundtrack, Midwest recording studios, outlandish music style, gritty rock, inventive band, raw band sound"
skills: "Psychedelic-garage-punk-rock’n’roll band from Cincinnati, Ohio"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff00ff # Bright magenta
  primary-rgb: "255,0,255" # Magenta RGB
  secondary: 008b8b # Electric cyan
  secondary-dark: ff9900 # Vibrant orange

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram 
    url: https://www.instagram.com/themuties
  - title: facebook
    url: https://www.facebook.com/p/The-Muties-100063560576799
  - title: bandcamp
    url: https://themuties.bandcamp.com
  - title: spotify
    url: https://open.spotify.com/artist/5uXXanx30i2X0zAZU4c9Ri
  - title: youtube
    url: https://www.youtube.com/@themuties2671

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
